apiVersion: v1
kind: Secret
metadata:
    name: ddclient-secret
    labels:
        app: ddclient
    namespace: ddns
stringData:
    ddclient.conf: ENC[AES256_GCM,data:6PDzkeSS+TYw9o3e66YzGZTSOWizcC2ewDI5hfIeNilUagVMXlklDCq67zKe63qX8h0Tu7QC7g44ActvPe+ObhvZiUyn9NWOI71u5vXRzvzc28fhrPxTK+CAi1CmN9R7vm57bzOJX1OEnKeBeXlVTrKgkuQxiV5xk430rTjmnpPfSMTppYTOKWkG4/GgsQV1IO2zYWuJAwbHnyTVWjk5qspiKHY2kC2LqmuwaYMQOAXSaULuZJr7hRsS8kYPggC88n9wG7tw6fJVkVGo7QBvqivZNuVweujcZ8vs6rps+HAd,iv:xbhkQpqKpq4sVpFWB8GBBVvuUU4H4Q8PcRZcqrQyHGw=,tag:5FAfPt/5MoKxoJl1XGqY0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-08-29T15:41:23Z"
    mac: ENC[AES256_GCM,data:/x6Fqc6DZnysC3+mL60ExRZr9PzXAZuKTwwYGCC1zq9i9ArmkcTyaD6y/bcZ1Vxy6kNRdMgMEQqcdJM+hrbje2C5jmeMxZvnKfPEzvAP/lEJnSmWrC8j+PmNXdlRCd1c7LGtGhxzYKj3I2pqBZGjr/uxpCzObgCWOmYThlTIDDQ=,iv:xUv1ZwJrsyyEX3BKT2doWz8dJQahhliji05E/XwqDpI=,tag:2VooS5o5b4MEHljOhhjS2g==,type:str]
    pgp:
        - created_at: "2021-08-29T15:41:23Z"
          enc: "-----BEGIN PGP MESSAGE-----\r\n\r\nhQIMA4DDztw18NWMARAAu3A5+oDraDKR+KsZpG3WV1/l64wZmU85vBJT1tIxAl6H\r\nuavmw03Ibf1nnvLwjGkuBc84/N+NgSCu04w+6aOFw0yGX75XczaJRTUXWo9Akjg0\r\nZSELVA/MEUyrHbhlrW5izRrVt2oYr4uktM9+tNoKSa2D5LOQSsR66NMpH+TlOrhC\r\n7neijIBanPGnPvQL/nroHvT5XQgrRaMQHP+qzwNZknrYYA5PyX9eMHdYCHz3qp3Q\r\nLkeH3Wc6xQilcA0snIfWS13de+rdDpKOyVpX1kGRZv1mhyuyjGZ5Pkw93/81yZi/\r\nLduV5ORNRBet2TIZ/Eud2oIRAFIlRpT3y7QvsinsZwS3PzC0vbymZPEv4Tz8xYwS\r\n97zTYg8RSRvreOdkNSjsUOKHRcPYGX8q5E9LsURNIOqOuQrIRs+qwTvxtZ2of3H+\r\n3jowqPrz3uy6h2L6PoMzsWPQeyYLAV0LjCUk3umGOjQUm8zEVWLtjyfWbNXFl6wi\r\nAzKTAsa0eZa29UiE5MrjbX97a4gsbKmn5kj1qVQ15YRt3OYK9AUSPIaMQ/SilDNK\r\n1W8QGwcQ+VH3wQVwGLvKUkvXpEhSS+ItcgDj863hhRDjtqTZMQnjR+ci+ezltnEj\r\n9qJ6qrZOKjz5SX9ptTtryAsxIFu3r22tmR2uvZhpUHLA9h3h/yywEz235XSfDwTS\r\nXgE+SkSs9XcP5Z1goXrMerOIYRFMQYzZZuYsiqIRA3nfFAqDwnSNxIGUld9C0aA9\r\nfrbzIVc7+XpOVt5kE5nGP1x5PQb4W7NoDD0R/ztmVW3C5wOe6P9w5kGdlU+M6Ts=\r\n=oi6q\r\n-----END PGP MESSAGE-----\r\n"
          fp: 6E65378796462A72C57F9D4E731C03C1D546A5CE
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
